# Generated by Django 3.1.6 on 2021-02-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitemodel',
            name='random_negative_text',
        ),
        migrations.RemoveField(
            model_name='websitemodel',
            name='random_positive_text',
        ),
    ]
