# Generated by Django 3.1.6 on 2021-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210209_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemodel',
            name='score',
            field=models.FloatField(),
        ),
    ]
