# Generated by Django 3.1.6 on 2021-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210209_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedWebsiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField()),
            ],
        ),
    ]
